# Generated by Django 2.2.13 on 2020-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200610_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sold_amount',
            field=models.IntegerField(blank=True, help_text="Nombre d'exemplaires vendus en millions", null=True, verbose_name="Nombre d'exemplaires vendus"),
        ),
    ]
